### ISSUE TITLE
big refresh after previous action

### ISSUE THREAD

**Issue by linuxcaffe** [linuxcaffe/tw-sched-sh#13]
Immediately after issuing a scheduling command, successful or unsuccessful, as long as an exit-command has not been issued, all elements of the tsch report should be refreshed and redrawn, ready to act on the next task(s).

**Comment by harleypig** [comment]
do you want to clear the screen at the beginning of each cycle? or just dump the next information and scroll the old up as it prints?

**Comment by linuxcaffe** [comment]
I was thinking the former, but now that you ask, maybe the latter would be best. What do you think?

**Comment by harleypig** [comment]
Ideally, it should be an option in a configuration file. :] But that's a ways off I think. My own preference is to clear the screen ... I have a hard time with clutter.

**Comment by linuxcaffe** [comment]
I agree, cleared it shall be!

**Comment by linuxcaffe** [comment]
There's no rush for this configuration option, but in regards to a configuration file, we already have one; sched.rc. i think we can just carry on using that method for any ole config, and as a super bonus, other task scripts could also read those settings (fwiw)

**Comment by harleypig** [comment]
_facepalm_ That's too obvious. _sigh_

**Comment by linuxcaffe** [comment]
After task command is executed, the output is important, to see what happened, so immediate refresh after execution might not be good. Perhaps a

Hit <enter> to continue (any other key to quit)

is indicated here ?

**Comment by linuxcaffe** [comment]
this is fixed ! (?)
