### ISSUE TITLE
bug: it's possible to modify more than sched:date and tag (should not be)

### ISSUE THREAD

**Issue by linuxcaffe** [linuxcaffe/tw-sched-sh#15]
Some thought has to go into ensuring that tsch doesn't molest non-schedule-related data. Maybe a closer look at the TASK_OPTS used.

**Comment by harleypig** [comment]
The only thing that is currently in TASK_OPTS is `rc.defaultwidth:90`.

To clarify, anything entered in the prompt is assumed to apply only to the `scheduled:` option, correct? Internally, tags may be assigned but the user won't be doing that. Correct?

**Comment by linuxcaffe** [comment]
Correct!

**Comment by linuxcaffe** [comment]
fixed!
