### ISSUE TITLE
prompt date and offset handling

### ISSUE THREAD

**Issue by linuxcaffe** [linuxcaffe/tw-sched-sh#5]
If the input at the prompt does not start with [0-9](max 4 digits) then the first argument is assumed to be a date (or date element, like 21st, mon, eow, etc)

Schedule ID > eom

should result in 

$ task $CAND_ID mod sched:eom  (Y/n)

if there is a second argument, it must be "-" or "+", and there must also be a third argument, so

Schedule ID > eom - 1wk

should result in 

$ task $CAND_ID mod sched:eom - 1wk  (Y/n)

**Comment by linuxcaffe** [comment]
Offset rules should also apply to ID [+|- offset, with minor variance that the ID is referenced, as in;

Schedule ID > 142 +3hr

becomes

$ task CAND_ID mod sched:142.scheduled + 3hr

**Comment by harleypig** [comment]
Is there a reason to force the spaces? `task ID mod sched:OID.scheduled + 3hr` chandes `ID` scheduled datetime to be `OID`'s scheduled datetime and the description to be changed to `+ 3hr`.

**Comment by linuxcaffe** [comment]
I thought the spaces would make it easier (possible) to parse, but if that's not the case, I like no-spaces too!

**Comment by linuxcaffe** [comment]
You hit a deadly bug! tsch really shouldn't be allowed to ever change a description! (See new issue)

**Comment by harleypig** [comment]
What are we parsing the input for if we're just dumping it in the `scheduled:` option? Are we supposed to be handling different dates different ways?

**Comment by linuxcaffe** [comment]
the only thing we need to parse, really, is to identify the ID part, as
there's a variation in handling. Everything else task handles (or doesn't)

**Comment by harleypig** [comment]
I've got most of the options covered, I think, but I'm having difficulty figuring out how to tell a date from an offset. See my [current code](https://github.com/harleypig/tw-sched-sh/blob/issue5_prompt_date_and_offset_handling/tsch.sh#L344).

The final options are what are giving me problems.

```
# Schedule cand_id > prompt == date          target_next == ''        task cand_id mod sched:$prompt
# Schedule cand_id > prompt == date          target_next == $ID_REGEX task cand_id mod sched:$prompt
# Sceduled cand_id > prompt == offset        target_next == ''        task cand_id mod sched:$prompt
# Sceduled cand_id > prompt == offset        target_next == $ID_REGEX task cand_id mod sched:$target_next.scheduled$prompt

# Schedule cand_id > prompt == $ID_REGEX date   target_next == ''        validate $ID_REGEX ; task cand_id mod sched:$prompt[1..]
# Schedule cand_id > prompt == $ID_REGEX date   target_next == $ID_REGEX validate $ID_REGEX ; task cand_id mod sched:$prompt[1..]
# Sceduled cand_id > prompt == $ID_REGEX offset target_next == ''        validate $ID_REGEX ; task cand_id mod sched:$prompt[0].scheduled$prompt[1..]
# Sceduled cand_id > prompt == $ID_REGEX offset target_next == $ID_REGEX validate $ID_REGEX ; task cand_id mod sched:$prompt[0].scheduled$prompt[1..]
```

A date is a fixed future point in time. eow, sow, etc. An offset is relative to a certain time, in this case a target task.

The problem I'm having is `1day` is an offset while `1st` is a date. `hr` is an offset while `eow` is a date.  So, I can't assume `^[0-9].*` and `[^0-9].*` is a date.

I've considered the following, and it may have to do for now.

If the first value matches $ID_REGEX then assume `task cand_id mod sched:$prompt[0].scheduled$prompt[1..]`
otherwise, assume `task cand_id mod sched:$prompt` and let the use deal with errors and what not.

What do you think?

**Comment by linuxcaffe** [comment]
I think that because "+|-" operators must lead an offset, a leading [0-9] can be assumed to be an id, else it can be assumed to be date. 

Whether or not the offset-operator (+|-) is surrounded by spaces, or no-spaces, would depend on what's easiest to parse for both tw and tsch. That gives us a consistent pattern. Could be;

ID
Date
ID+offset
Date+offset
+offset

Imho, target_next_id should only be automatically chosen, if [[ prompt == '' && target list != '' ]]  and not in the case of [[ prompt == "+ something" ]] which should always mean "offset from now", regardless of target list.

**Comment by harleypig** [comment]
My initial thought is a simple one, and has only to do with your last paragraph.

`prompt == "+ something"` should always be `task cand_id mod sched:"+ something"` ... what if I want the task to be scheduled 3 hrs after target_next? I would want `prompt == "+3hr"` to do `task cand_id mod sched:"target_next.scheduled+3hr"`

**Comment by harleypig** [comment]
Crap ... just had a thought and wanted to get it down somewhere.  It's possible for a prompt to start with a minus (`-`) ... `task 3 mod sched:target_next.scheduled-1day` ...

Edit: minus is spelled with an s.

**Comment by harleypig** [comment]
Hmmm ... let's back this up.

The meat of this is, we need to set the scheduled attribute for `Schedule <task(s)>`. Ignoring conditions that we (may or may not) want to block we're looking for something like

```
Schedule $tasks > $setting
```

which we want to convert to

```
$setting[0] =~ $ID_REGEX
  task $tasks modify scheduled:$setting[0].scheduled$setting[1..]
elsif $target_next =~ $ID_REGEX
  task $tasks modify scheduled:$target_next.scheduled$setting
else
  #task $tasks modify scheduled:$setting
  #or error and prompt
```

If this is the case, I don't need to do any complicated error checking. I can use `task calc ...` to determine if it's a valid setting, then convert the calculated date to epoch seconds and see if it's before now.

**Comment by linuxcaffe** [comment]
On Jan 15, 2016 10:10 PM, "Alan Young" notifications@github.com wrote:
sched:"+ something" ... what if I want the task to be scheduled 3 hrs after
target_next? I would want prompt == "+3hr" to do task cand_id mod
sched:"target_next.scheduled+3hr"

I think, in that case, that you should have to enter target next I'd first,
like prompt == 142+3hr. Otherwise the application of "just +offset" would
be inconsistent, depending on what, if anything, was in the target list.
